//Apps Script

const SOURCE = [
	["#ff0000", "#000000"],
	["#000000", "#ff0000"]
];// Generated by imgto.js

/*function zerolessRebase(input, base){
	let overflows = Math.floor(input / base);
	let horse = input % base;
	if (overflows > 0){
		return zerolessRebase(overflows - 1, base).concat(horse);
	} else {
		return [horse]
	}
}*/

function fwoosh() {
	//const ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
	// let colIdToLetter = id => zerolessRebase(id, 26).map(i => ALPHABET[i]).join("");
	// let getCell = (x, y) => colIdToLetter(x) + y;

	let width = SOURCE[0].length;
	let height = SOURCE.length;
	let sheet = SpreadsheetApp.getActiveSheet();
	//let range = SpreadsheetApp.getActiveSheet().getRange("A1:" + getCell(WIDTH - 1, height));
	let range = sheet.getRange(1, 1, height, width);

	range.setBackgrounds(SOURCE);
	sheet.setRowHeights(1, height, 5);
	sheet.setColumnWidths(1, width, 4);
	sheet.setHiddenGridlines(true);
}

fwoosh();